config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # ERRORS
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Defines the root path route ("/")
  root "static_pages#home"
  get '/about', to: 'static_pages#about'
  
  # PWA service_worker
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline" => "service_worker#offline"
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  resources :dive_sites, only: [:index, :show, :edit, :update]
  resources :dive_centers, only: [:index, :show, :edit, :update]
  resources :geo_groups, only: [:index, :show, :edit, :update]
  resources :countries, only: [:index, :show, :edit, :update]

  # Regions
  get '/:country/:region/', 
    to: 'regions#show', 
    as: 'region'
  get '/regions/:id/edit', 
    to: 'regions#edit', 
    as: 'edit_region'
  patch '/regions/:id', 
    to: 'regions#update', 
    as: 'update_region'
  
  # Cities
  get '/cities/:id/edit', # Always put this line on top to avoid colision with #show
    to: 'cities#edit', 
    as: 'edit_city' 
  get '/:country/:region/:city/', 
    to: 'cities#show', 
    as: 'city'
  patch '/cities/:id', 
    to: 'cities#update', 
    as: 'update_city'

#  resources :destinations, only: [:index] do
#    get ':country', to: 'destinations#country', on: :collection, as: 'country'
#    get ':country/:region', to: 'destinations#region', on: :collection, as: 'region'
#    get ':country/:region/:city', to: 'destinations#city', on: :collection, as: 'city'
#  end
  
  
end

app/models/country.rb
class Country < ApplicationRecord
  
  include AlgoliaSearch
  include Rails.application.routes.url_helpers
  extend FriendlyId
  friendly_id :name, use: :slugged
  reverse_geocoded_by :latitude, :longitude
  
  # ============= relations ============
  
  has_one_attached :main_image
  
  has_many :geo_groups_countries, dependent: :destroy
  has_many :geo_groups, through: :geo_groups_countries
  
  has_many :regions
  has_many :cities, through: :regions
  has_many :dive_centers
  has_many :dive_sites

  # ============= validations ============
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :phone_prefix, format: { with: /\A\+\d+\z/, message: "should start with '+' followed by numbers" }, allow_blank: true
  validates :code, format: { with: /\A[A-Z]{2}\z/, message: "should be 2 upcase letters" }

  # ============= scopes ============


  # ============= methods ===========
  
  def waters
    geo_groups.water
  end
  
  def continent
    geo_groups.continent.first
  end
  
  # ============= algolia ===========
  
  algoliasearch do
    attributes :name, :full_path, :l_kind, :l_geo_refs
    searchableAttributes ['name']
    
    # later : add popularity score with 
    # customRanking ['desc(popularity_score)']
    
    geoloc :latitude, :longitude
  end
  
  def full_path
    country_path(self)
  end
  
  def l_kind
    I18n.t("models.countries.kinds.country").capitalize
  end
  
  def l_geo_refs
    I18n.t("models.countries.geo_refs", 
      continent: self.continent.name, 
      waters: self.waters.map(&:name).to_sentence,
      count: self.waters.size
    )
  end
  
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  
  before_action :set_country, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :must_be_admin, only: [:edit, :update]
  
  def index
    @countries = Country.all  
  end
  
  def show
    @regions = @country.regions.order(cities_count: :desc)
    @locations = Maps::CreateLocationHashes.new([@country, @regions].flatten, boundaries: :country).perform
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "#{@country.name} has been successfuly updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  private 

  def set_country
    @country = Country.friendly.find(params[:id]).decorate
  end

  def must_be_admin
    current_user.admin?
  end

  def country_params
    params.require(:country).permit(:name, :description, :latitude, :longitude, :code, :demonym, :currency, :pressure, :phone_prefix, :voltage, :plug, :meta_description, :slug)
  end
  
end

app/views/countries/show_components/_heading.html.erb
<div class="container px-4 bg-white mt-12 mb-12 sm:mt-36 sm:mb-20 mx-auto">
  <div class="grid sm:grid-cols-2 gap-4 my-12 sm:my-20">
    <div class="py-2 sm:py-10 xl:pr-20">
      <%= render Ui::BreadcrumbsComponent.new([
          { 
            path: geo_groups_path, 
            text: "Destinations" 
          },
          { 
            path: geo_group_path(@country.continent), 
            text: @country.continent.name 
          },
          { 
            path: country_path(@country), 
            text: @country.name 
          },
        ])
      %>
      <h1 class="heading-1">
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to edit_country_path(@country) do %>
            <i class="fa-duotone fa-pen-to-square" style="--fa-primary-color: #0ea5e9; --fa-secondary-color: #0ea5e9;"></i>
          <% end %>
        <% end %>
        <%= ISO3166::Country.new(@country.code).emoji_flag %>
        Diving in <%= @country.name %>
      </h1>
      <p class="mt-4 sm:mt-8 paragraph">
        <%= @country.description %>
      </p>
    </div>
    <div>
      <%= image_tag(@country.main_image_path, class: "rounded-4xl shadow-xl") %>
    </div>
  </div>
</div>

app/views/countries/show_components/_informations.html.erb
<div class="container px-4 mx-auto mt-8 sm:mt-0 sm:mb-28">
  <h2 class="heading-1">
    What to know about <%= @country.name %>?
  </h2>
  <div class="mt-10 w-full p-2 bg-white rounded-lg shadow sm:p-6">
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-8 sm:gap-12">
      <% if @country.languages.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Languages</span><br>
          <span class="text-xl"><%= to_sentence(@country.languages) %></span>
        </div>
      <% end %>
      <% if @country.demonym.present? %> 
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Demonym</span><br>
          <span class="text-xl"><%= @country.demonym %></span>
        </div>
      <% end %>
      <% if @country.currency.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Currency</span><br>
          <span class="text-xl"><%= @country.currency %></span>
        </div>
      <% end %>
      <% if @country.pressure.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Pressure</span><br>
          <span class="text-xl"><%= @country.pressure %></span>
        </div>
      <% end %>
      <% if @country.phone_prefix.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Phone prefix</span><br>
          <span class="text-xl"><%= @country.phone_prefix %></span>
        </div>
      <% end %>  
      <% if @country.voltage.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Voltage</span><br>
          <span class="text-xl"><%= @country.voltage %></span>
        </div>
      <% end %>
      <% if @country.plug.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Plug</span><br>
          <span class="text-xl"><%= @country.plug %></span>
        </div>
      <% end %>
      <% if @country.international_airports.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">International airports</span><br>
          <span class="text-xl"><%= to_sentence(@country.international_airports) %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/countries/show_components/_map.html.erb
<%= render Ui::Containers::WavesComponent.new do %>
  <div class="container px-4 mx-auto">
    <h2 class="heading-1">
      Where to dive in <%= @country.name %>?
    </h2>
    <div class="grid sm:grid-cols-2 gap-12 mt-10" data-controller="map"
      data-map-locations="<%= @locations.to_json %>"
      data-map-zoom-level="5"
      data-map-destination-marker-url="<%= image_url('map_markers/location-sky-orange.png') %>"
      data-map-dive-center-marker-url="<%= image_url('map_markers/dive_center.png') %>"
      data-map-dive-site-marker-url="<%= image_url('map_markers/dive_site.png') %>"
      data-map-mapbox-token="<%= ENV["MAPBOX_ACCESS_TOKEN"] %>"
    >
      <div id="map" class="w-full h-full min-h-[65vh] max-h-[100vh] rounded-4xl shadow-lg">
        <!--  javascript/controllers/map_controller.js   -->
      </div>
      <div>
        <h3 class="heading-3">
          Discover <%= @country.regions_count %> regions in <%= @country.name %>
        </h3>
        <div class="grid grid-cols-2 gap-2">
          <% @regions.includes([:cities]).first(10).each do |region| %>
            <%= link_to region_path(country: @country.slug, region: region.slug) do %>
              <div class="mt-2 w-full h-full p-2 bg-white rounded-lg shadow sm:p-6 hover:shadow-lg">
                <p class="link text-pretty"><%= region.name %></p>
                <p class="text-balance">
                  <%= t("count.x_cities", count: region.cities_count) %>,
                  <%= t("count.x_dive_sites", count: region.cities.sum(&:dive_sites_count)) %>,
                  <%= t("count.x_dive_centers", count: region.cities.sum(&:dive_centers_count)) %>
                </p>
              </div>
            <% end %>
          <% end %>
        </div>
        <% if @country.regions_count > 10 %>
          <div class="btn-primary my-5">
            <i class="fas fa-plus"></i> See <%= @country.regions_count - 10 %> more regions
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>