config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # ERRORS
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Defines the root path route ("/")
  root "static_pages#home"
  get '/about', to: 'static_pages#about'
  
  # PWA service_worker
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline" => "service_worker#offline"
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  resources :dive_sites, only: [:index, :show, :edit, :update]
  resources :dive_centers, only: [:index, :show, :edit, :update]
  resources :geo_groups, only: [:index, :show, :edit, :update]
  resources :countries, only: [:index, :show, :edit, :update]

  # Regions
  get '/:country/:region/', 
    to: 'regions#show', 
    as: 'region'
  get '/regions/:id/edit', 
    to: 'regions#edit', 
    as: 'edit_region'
  patch '/regions/:id', 
    to: 'regions#update', 
    as: 'update_region'
  
  # Cities
  get '/cities/:id/edit', # Always put this line on top to avoid colision with #show
    to: 'cities#edit', 
    as: 'edit_city' 
  get '/:country/:region/:city/', 
    to: 'cities#show', 
    as: 'city'
  patch '/cities/:id', 
    to: 'cities#update', 
    as: 'update_city'

#  resources :destinations, only: [:index] do
#    get ':country', to: 'destinations#country', on: :collection, as: 'country'
#    get ':country/:region', to: 'destinations#region', on: :collection, as: 'region'
#    get ':country/:region/:city', to: 'destinations#city', on: :collection, as: 'city'
#  end
  
  
end

app/models/dive_center.rb
class DiveCenter < ApplicationRecord
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  reverse_geocoded_by :latitude, :longitude
  
  # ============= relations ==============
  
  has_many_attached :images
  
  has_many :dive_centers_affiliations
  has_many :affiliations, through: :dive_centers_affiliations
  has_many :dive_centers_activities
  has_many :activities, through: :dive_centers_activities
  
  belongs_to :destination, counter_cache: true, optional: true
  belongs_to :geo_group, counter_cache: true, optional: true
  belongs_to :country, counter_cache: true, optional: true
  belongs_to :region, counter_cache: true, optional: true
  belongs_to :city, counter_cache: true, optional: true
  
  # ============= validations ============
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :web_url, allow_nil: true, length: { maximum: 255 }, format: { with: URI::DEFAULT_PARSER.make_regexp }, unless: -> { web_url.nil? }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :street, presence: true, length: { maximum: 255 }
  validates :city, allow_nil: true, length: { maximum: 255 }
  validates :state, allow_nil: true, length: { maximum: 255 }, unless: -> { state.nil? }
  validates :zip, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :country_code, presence: true, length: { is: 2 }
#  validates :phone_number, allow_nil: true, format: {
#    with: /\A\+?\d+(\s*[-\/()]*\s*\d+)*\z/,
#    message: "must be a valid phone number"
#  }, unless: -> { phone_number.nil? }
  
  # =============== scopes =====================
  
end

app/controllers/dive_centers_controller.rb
class DiveCentersController < ApplicationController
  
  def index
    @pagy, @dive_centers = pagy(DiveCenter.all.includes([:city, :region, :country]))
  end

  def show
    @dive_center = DiveCenter.friendly.find(params[:id])
    @closest_dive_sites = DiveSite.near(@dive_center.to_coordinates, 50, units: :km).first(5)
    @locations = create_locations_array
  end
  
  private
  
  def create_locations_array
    dive_center_location = Maps::CreateLocationHashes.new([@dive_center]).perform
    dive_sites_around_locations = Maps::CreateLocationHashes.new(@closest_dive_sites).perform
    
    dive_center_location + dive_sites_around_locations
  end
  
end

app/views/dive_centers/index.html.erb
<div class="container bg-white mt-36 mb-20 mx-auto">
  <h1 class="heading-1">
    Find your next 
    <span class="line-through text-gray-500">center</span> 
    <span class="bold text-main-sky">community</span>.
  </h1>
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-8">
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">
            Dive center
          </th>
          <th scope="col" class="px-6 py-3">
            City
          </th>
          <th scope="col" class="px-6 py-3">
            Country code
          </th>
          <th scope="col" class="px-6 py-3">
            Activities
          </th>
        </tr>
      </thead>
      <tbody>
        <% @dive_centers.each do |dive_center| %>
          <tr class="bg-white border-b hover:bg-sky-50">
            <th scope="row" class="px-6 py-4">
              <%= link_to dive_center.name.titleize, dive_center_path(dive_center), class: "link" %>
            </th>
            <td class="px-6 py-4">
              <%= dive_center.city&.name %>
            </td>
            <td class="px-6 py-4">
              <%= dive_center.city&.country&.name %>
            </td>
            <td class="px-6 py-4">
              <%= dive_center.activities.visible.pluck(:name).to_sentence&.capitalize %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-center mt-10">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
</div>

app/views/dive_centers/show.html.erb
<div class="container bg-white mt-36 mb-20 mx-auto">
  <nav class="flex mb-4" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
      <li class="inline-flex items-center">
        <%= link_to root_path, class: "inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600" do %>
          <svg class="w-3 h-3 mr-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
          </svg>
          Home
        <% end %>
      </li>
      <li class="inline-flex items-center">
        <%= link_to dive_centers_path, class: "inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600" do %>
          <span class="inline-flex items-center text-sm font-medium text-gray-700">
           <svg class="w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            Dive Centers
          </span>
        <% end %>
      </li>
      <% unless @dive_center.city.blank? %>
        <li class="inline-flex items-center">
          <span class="inline-flex items-center text-sm font-medium text-gray-700">
           <svg class="w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <%= @dive_center.city.country.name %>
          </span>
        </li>
        <li>
          <div class="flex items-center">
            <svg class="w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="ml-1 text-sm font-medium text-gray-700 md:ml-2">
              <%= @dive_center.city.name.titleize %>
            </span>
          </div>
        </li>
      <% end %>
    </ol>
  </nav>
  <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
    <%= @dive_center.name.titleize %>
  </h1>
  
  <div class="bg-sky-50 mx-auto rounded-lg shadow mt-10 p-5">
    <ul class="flex flex-wrap items-center justify-center text-gray-900 text-xl list-none text-center">
      <li class="font-semibold m-5">
        <%= @dive_center.city.country.name %> 
        <%= "- #{@dive_center.city.name}" unless @dive_center.city.blank? %> <br>
        <span class="text-sm font-normal">Location</span>
      </li>
      <li class="font-semibold m-5">
        <%= @dive_center.latitude %>, <%= @dive_center.longitude %><br>
        <span class="text-sm font-normal">Coordinates</span>
      </li>
      <% unless @dive_center.activities.blank? %>
        <li class="font-semibold m-5">
          <%= @dive_center.activities.visible.pluck(:name).to_sentence&.capitalize %><br>
          <span class="text-sm font-normal">Activities</span>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="grid grid-cols-2 gap-4 mt-10">
    <div data-controller="map" 
      data-map-locations="<%= @locations.to_json %>"
      data-map-zoom-level="15"
      data-map-destination-marker-url="<%= image_url('map_markers/destination.png') %>"
      data-map-dive-center-marker-url="<%= image_url('map_markers/dive_center.png') %>"
      data-map-dive-site-marker-url="<%= image_url('map_markers/dive_site.png') %>"
      data-map-mapbox-token="<%= ENV["MAPBOX_ACCESS_TOKEN"] %>"
    >
      <div id="map" class="w-full h-full min-h-[65vh]"></div>
    </div>
    <div class="w-full  p-4 bg-white rounded-lg shadow sm:p-8">
      <div class="flex items-center justify-between mb-4">
        <h5 class="text-xl font-bold leading-none text-gray-900">Closest sites</h5>
      </div>
      <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200">
          <% @closest_dive_sites.each do |site| %>
            <li class="p-2 sm:p-4 hover:bg-sky-100">
              <div class="flex items-center">
                <div class="flex-1 min-w-0 ms-4">
                  <%= link_to site.name.titleize, dive_site_path(site), class: "text-sm font-medium text-sky-600 underline truncate" %>
                  <p class="text-sm text-gray-500 truncate">
                    <%= site.bow.titleize %>
                  </p>
                </div>
                <div class="inline-flex items-center text-base font-semibold text-gray-900">
                  <%= @dive_center.distance_to(site.to_coordinates, :km).round(1) %>km
                </div>
              </div>
            </li>
          <% end %>
          <% if @closest_dive_sites.blank? %>
            <p class="text-sm text-gray-500">
              No other dive sites listed around, yet.
            </p>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>