config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # ERRORS
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Defines the root path route ("/")
  root "static_pages#home"
  get '/about', to: 'static_pages#about'
  
  # PWA service_worker
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline" => "service_worker#offline"
  
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  
  resources :dive_sites, only: [:index, :show, :edit, :update]
  resources :dive_centers, only: [:index, :show, :edit, :update]
  resources :geo_groups, only: [:index, :show, :edit, :update]
  resources :countries, only: [:index, :show, :edit, :update]

  # Regions
  get '/:country/:region/', 
    to: 'regions#show', 
    as: 'region'
  get '/regions/:id/edit', 
    to: 'regions#edit', 
    as: 'edit_region'
  patch '/regions/:id', 
    to: 'regions#update', 
    as: 'update_region'
  
  # Cities
  get '/cities/:id/edit', # Always put this line on top to avoid colision with #show
    to: 'cities#edit', 
    as: 'edit_city' 
  get '/:country/:region/:city/', 
    to: 'cities#show', 
    as: 'city'
  patch '/cities/:id', 
    to: 'cities#update', 
    as: 'update_city'

#  resources :destinations, only: [:index] do
#    get ':country', to: 'destinations#country', on: :collection, as: 'country'
#    get ':country/:region', to: 'destinations#region', on: :collection, as: 'region'
#    get ':country/:region/:city', to: 'destinations#city', on: :collection, as: 'city'
#  end
  
  
end

app/models/city.rb
class City < ApplicationRecord
  
  include AlgoliaSearch
  include Rails.application.routes.url_helpers
  extend FriendlyId
  friendly_id :name, use: :slugged
  reverse_geocoded_by :latitude, :longitude
  
  # ============= callbacks ============
  
  after_create :increment_country_counter # Counter cache de country has_many city through region
  after_destroy :decrement_country_counter
  
  # ============= relations ============
  
  has_one_attached :main_image
  
  belongs_to :region, counter_cache: true
  has_many :dive_centers
  has_many :dive_sites

  # ============= validations ============
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }


  # ============= scopes ============


  # ============= methods ===========
  
  def country
    region.country
  end
  
  def geo_groups
    country.geo_groups
  end
  
  def waters
    geo_groups.waters
  end
  
  def continent
    geo_groups.continent.first
  end
  
  # ============= algolia ===========
  
  algoliasearch do
    attributes :name, :full_path, :l_kind, :l_geo_refs
    searchableAttributes ['name']
    
    # later : add popularity score with 
    # customRanking ['desc(popularity_score)']
    
    geoloc :latitude, :longitude
  end
  
  def full_path
    city_path(city: self, region: self.region, country: self.country)
  end
  
  def l_kind
    I18n.t("models.cities.kinds.city").capitalize
  end
  
  def l_geo_refs
    I18n.t("models.cities.geo_refs", country: self.country.name, region: self.region.name)
  end
  
  private
  
  def increment_country_counter
    country = self.country
    country.update_columns(cities_count: country.cities_count + 1)
  end

  def decrement_country_counter
    country = self.country
    country.update_columns(cities_count: country.cities_count - 1)
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :must_be_admin, only: [:edit, :update]
  
  def show
    @city = City.friendly.find(params[:city]).decorate
    @dive_centers = @city.dive_centers
    @dive_sites = @city.dive_sites
    
    dive_locations = Maps::CreateLocationHashes.new(@dive_sites + @dive_centers).perform
    city_location = Maps::CreateLocationHashes.new([@city], boundaries: :city).perform
    @locations = city_location + dive_locations
  end
  
  def edit
    @city = City.friendly.find(params[:id])
  end

  def update
    @city = City.friendly.find(params[:id])
    
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_path(country: @city.country, region: @city.region, city: @city), notice: "#{@city.name} has been successfuly updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  private 
  
  def must_be_admin
    current_user.admin?
  end

  def city_params
    params.require(:city).permit(:name, :description, :latitude, :longitude, :slug, :timezone, :capital_city)
  end

  
end

app/views/cities/show_components/_heading.html.erb
<div class="container px-4 bg-white mt-12 mb-12 sm:mt-36 sm:mb-20 mx-auto">
  <div class="sm:grid sm:grid-cols-2 gap-4 my-12 sm:my-20">
    <div class="py-2 sm:py-10 xl:pr-20">
      <%= render Ui::BreadcrumbsComponent.new([
          { 
            path: geo_groups_path, 
            text: "Destinations" 
          },
          { 
            path: geo_group_path(@city.continent), 
            text: @city.continent.name 
          },
          { 
            path: country_path(@city.country), 
            text: @city.country.name 
          },
          { 
            path: region_path(country: @city.country, region: @city.region), 
            text: @city.region.name 
          },
          { 
            path: city_path(country: @city.country.slug, region: @city.region.slug, city: @city.slug ), 
            text: @city.name 
          },
        ])
      %>
      <h1 class="heading-1">
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to edit_city_path(@city.id) do %>
            <i class="fa-duotone fa-pen-to-square" style="--fa-primary-color: #0ea5e9; --fa-secondary-color: #0ea5e9;"></i>
          <% end %>
        <% end %>
        <%= ISO3166::Country.new(@city.country.code).emoji_flag %>
        Diving in <%= @city.name %>
      </h1>
      <p class="mt-4 sm:mt-8 paragraph">
        <%= @city.description.present? ? @city.description : @city.country.description %>
      </p>
    </div>
    <div class="">
      <%= image_tag(@city.main_image_path, class: "rounded-4xl shadow-xl") %>
    </div>
  </div>
</div>

app/views/cities/show_components/_informations.html.erb
<div class="container px-4 mx-auto mt-8 sm:mt-0 sm:mb-28">
  <h2 class="heading-1">
    What to know about <%= @city.country.name %>?
  </h2>
  <div class="mt-10 w-full p-2 bg-white rounded-lg shadow sm:p-6">
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-8 sm:gap-12">
      <% if @city.country.languages.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Languages</span><br>
          <span class="text-xl"><%= to_sentence(@city.country.languages) %></span>
        </div>
      <% end %>
      <% if @city.country.demonym.present? %> 
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Demonym</span><br>
          <span class="text-xl"><%= @city.country.demonym %></span>
        </div>
      <% end %>
      <% if @city.country.currency.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Currency</span><br>
          <span class="text-xl"><%= @city.country.currency %></span>
        </div>
      <% end %>
      <% if @city.country.pressure.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Pressure</span><br>
          <span class="text-xl"><%= @city.country.pressure %></span>
        </div>
      <% end %>
      <% if @city.country.phone_prefix.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Phone prefix</span><br>
          <span class="text-xl"><%= @city.country.phone_prefix %></span>
        </div>
      <% end %>  
      <% if @city.country.voltage.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Voltage</span><br>
          <span class="text-xl"><%= @city.country.voltage %></span>
        </div>
      <% end %>
      <% if @city.country.plug.present? %>  
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">Plug</span><br>
          <span class="text-xl"><%= @city.country.plug %></span>
        </div>
      <% end %>
      <% if @city.country.international_airports.present? %>
        <div class="text-center text-2xl">
          <span class="font-serif text-main-sky">International airports</span><br>
          <span class="text-xl"><%= to_sentence(@city.country.international_airports) %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cities/show_components/_map.html.erb
<%= render Ui::Containers::WavesComponent.new do %>
  <div class="container px-4 mx-auto">
    <h2 class="heading-1">
      Where to dive in <%= @city.name %>?
    </h2>
    <div class="grid sm:grid-cols-2 gap-12 mt-7" data-controller="map"
      data-map-locations="<%= @locations.to_json %>"
      data-map-zoom-level="12"
      data-map-destination-marker-url="<%= image_url('map_markers/location-dark-sky.png') %>"
      data-map-dive-center-marker-url="<%= image_url('map_markers/dive_center.png') %>"
      data-map-dive-site-marker-url="<%= image_url('map_markers/dive_site.png') %>"
      data-map-mapbox-token="<%= ENV["MAPBOX_ACCESS_TOKEN"] %>"
    >
      <div id="map" class="w-full h-full min-h-[65vh] max-h-[70vh] rounded-4xl shadow-lg z-0">
        <!--  javascript/controllers/map_controller.js   -->
      </div>
      <div>
        <h3 class="heading-3">
          Discover <%= t("count.x_dive_sites", count: @city.dive_sites_count) %>
          and <%= t("count.x_dive_centers", count: @city.dive_centers_count) %>
          in <%= @city.name %>
        </h3>
        <div class="grid grid-cols-2 gap-2">
          <div>
            <% @dive_sites.first(7).each do |site| %>
              <%= link_to dive_site_path(site) do %>
                <div class="mt-2 w-full p-4 bg-white rounded-lg shadow hover:shadow-lg">
                  <p class="font-medium text-main-sky whitespace-nowrap">
                    <%= image_tag("map_markers/dive_site.png", class: "w-[1.7em] inline") %>
                    <span class="underline text-balance"><%= site.name.titleize %></span>
                  </p>
                </div>
              <% end %>
            <% end %>
            <% if @city.dive_sites_count > 7 %>
              <div class="my-3 btn-primary">
                <i class="fas fa-plus"></i> See <%= @city.dive_sites_count - 7 %> more sites in <%= @city.name %>
              </div>
            <% end %>
          </div>
          <div>
            <% @dive_centers.first(7).each do |center| %>
              <%= link_to dive_center_path(center) do %>
                <div class="mt-2 w-full p-4 bg-white rounded-lg shadow hover:shadow-lg">
                  <p class="font-medium text-main-sky whitespace-nowrap">
                    <%= image_tag("map_markers/dive_center.png", class: "w-[1.7em] inline") %>
                    <span class="underline text-balance"><%= center.name.titleize %></span>
                  </p>
                </div>
              <% end %>
            <% end %>
            <% if @city.dive_centers_count > 7 %>
              <div class="btn-primary my-5">
                <i class="fas fa-plus"></i> See <%= @city.dive_centers_count - 7 %> more centers in <%= @city.name %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>